apiVersion: v1
kind: Service
metadata:
  labels:
    run: kubernetes-kevin-2
  name: kubernetes-kevin-2
  namespace: default
spec:
  clusterIP: 10.35.251.177
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31115
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: kubernetes-kevin-2
  sessionAffinity: None
  type: LoadBalancer